Sprint 1/step 2
4Evgenia/react-burger pull request #4
Opened 2021-12-10 23:08 UTC by 4Evgenia

2021-12-11 23:04 UTC, grishbar requested changes
Отличная работа, код чистый и легко читаемый, везде абсолютно верно описаны proptypes. Круто, что все компоненты написаны в функциональном стиле, и что воспользовалась очень полезными библиотекми используемыми в продакшен коде как ErrorBoundary. Отдельный лайк, за то, что все уже написано на typescript.
Есть небольшие недочеты, которые надо исправить для принятия работы:

- [ ] Вынести создание объектов из jsx
- [ ] Обработать repsonse.ok в запросе
- [ ] Избавиться от "магических" переменных

2021-12-11 23:04 UTC, grishbar commented on src/components/app/app.tsx
> +import ErrorBoundary from '../shared/error-boundary';
`отлично`
Круто, что все компоненты написаны на typescript. Также классно что заиспользовала errobundary, для отлова и показа ошибок

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: any) => {
`можно лучше`
сейчас не ошибка, на следующих этапах, когда будем переписывать проект на typescript будет ошибкой, так как any бфть в проекте не должно, и props компонента всегда должны быть типизированы

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +    const [activeTab, setActiveTab] = React.useState(() => props.tabs[0].type);
`надо исправить`
для чего передаешь функцию в useState? там должно быть сразу вот такое:  props.tabs[0].type

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +                            />))}
`можно лучше`
лучше вынеси в компонент и создай там объект с типами и ингредиентами для каждого типа и маппайся по нему, так как сейчас ты при каждом ререндере создаешь три новых массива, что негативно влияет на напроизводительность, старайся не создавать в jsx новые объекты.
Также свойство data надо переименовать таких абстрактных имен переменных быть не должно, переменная должна явно отражать, что в ней содержится

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/constructor-item/constructor-item.css
> +}
`можно лучше`
старайся избегать комбинаторов по возможности, очень тяжело в будущем поддерживать такой код, и он очень чреват неожиданными багами, лучше всегда сделать отдельный класс и задать стили под него

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/constructor-item/constructor-item.css
> +    bottom: 0.4rem;
`можно лучше`
почему тут заиспользовала относительные переменные, кажется все можно сделать статичными px, если что то делаешь то относительными, то весь проект должен быть такой

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-constructor/constructor-item/constructor-item.tsx
> +    const {ingredient, onSelectIngredient} = props;
`можно лучше`
эту деструктуризацию можно сделать строчкой выше:
```
const ConstructorItem = ({ingredient, onSelectIngredient}) => {
```

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +                    let suffix = index === 0 ? "(вверх)" : index === props.selectedIngredients.length - 1 ? "(низ)" : "";
`надо исправить`
- Это const а не let.
- Старайся никогда не писать вложенные тернарники, это очень плохая практика, так как такой код зачастаю совсем нечитаемый, есть даже правила линтера в популярных настройках, которые это запрещают делать

2021-12-11 23:04 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +                    <span className="price mr-2">{props.selectedIngredients.reduce(((acc:number, ing:any) => ing.price + acc), 0)}</span>
`надо исправить`
вынеси этот подсчет суммы в компонент, также отличное место, чтобы вопспользоваться [useMemo](https://ru.reactjs.org/docs/hooks-reference.html#usememo)

2021-12-11 23:04 UTC, grishbar commented on src/components/layout/app-header/header.css
> +}
`можно лучше`
такое тоже очень плохая практика, так как у тебя может поменяться jsx там передвинут компоненты, а css файлы никто смотреть не будет, в итоге получится баг, старайся всегда стили давать только по классам так намного надежней, проще масштабируется и легче дебажится

2021-12-11 23:04 UTC, grishbar commented on src/components/layout/app-header/header.tsx
> +const PROFILE = "Личный кабинет";
`отлично`
круто, что вынесла магические слова в константы снаружи компонента

2021-12-11 23:04 UTC, grishbar commented on src/components/layout/main/main.tsx
> +             })
`надо исправить`
не совсем очевидно, но если запрос выполнится и придет с 500 ошибкой с данными об этой ошибкой твой код попадет в блок then, а не в блок catch, так, что нужно еще добавить обработку на [Response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok), и если она проваливается, то выкидывать ошибку, чтобы провалиться в блок catch

2021-12-11 23:04 UTC, grishbar commented on src/components/layout/modal/modal.tsx
> +        if (event.keyCode === 27)
`надо исправить`
такихмагических чисел не должно быть в коде, вынеси пожалуйста число из компонента, и дай ему осмысленное название

2021-12-12 13:11 UTC, 4Evgenia commented on src/components/layout/main/main.tsx
> +             })
Поправила

2021-12-12 13:12 UTC, 4Evgenia commented on src/components/layout/app-header/header.css
> +}
Поправила

2021-12-12 13:19 UTC, 4Evgenia commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: any) => {
Я изначально создавала интерфейсы для всех пропсов (можно посмотреть в промежуточной работе), но в задании указано, что нужно делать на PropTypes. Мне непонятен смысл иметь и то и другое в проекте, так как когда используем интерфейсы тайпскрипта мы заведомо не можем передать в компонент невалидные пропсы и вроде как будто проптайпы в этом случае не нужны. Так как указано что сейчас используем проптайпсы я удалила все интерфейсы пропсов.

2021-12-13 01:13 UTC, grishbar commented
Отлично, все критичные проблемы испрвлены, работу принимаю, удачи в дальнейшем обучении

2021-12-13 15:28 UTC, merged